################################################
# YnFOR — Configuration principale
# Version : 1.0
# Auteur  : Teremu
###############################################

###############
# ENVIRONNEMENT
###############
# production | development | testing
ENV=production

#################
# NIVEAU DE LOGS
#################
# info | warn | error | debug
LOG_LEVEL=info

#########################
# MODULES — AUTO-CHARGEMENT
#########################
# active | inactive
MODULES_AUTOLOAD=active

# Dossier contenant les modules YnFOR
MODULES_DIR=modules

#########################
# RUNTIME
#########################
# active | inactive
VALIDATION_ON_START=active
LOAD_MODULES_ON_START=active

#########################
# CHEMINS INTERNES
#########################
CORE_DIR=core
INFRA_DIR=core/infra
ASSETS_DIR=assets
DOCS_DIR=docs
TESTS_DIR=tests

#########################
# OPTIONS AVANCÉES
#########################
# active | inactive
STRICT_STRUCTURE=active
ALLOW_OPTIONAL_DIRS=inactive

# active | inactive
ENABLE_REGISTRY_UPDATE=active

#########################
# METADONNÉES
#########################
PROJECT_NAME=YnFOR
PROJECT_VERSION=1.0
